#!/bin/bash

XCVERSION=1.1

grep -i Requires: SPECS/postgresxc-$XCVERSION.spec | awk '{print $2}' | uniq | grep -v '{name}' | xargs sudo yum install -y || exit ?
spectool -S -C SOURCES -g SPECS/postgresxc-$XCVERSION.spec || exit $?
rpmbuild -ba --define "_topdir `pwd`" SPECS/postgresxc-$XCVERSION.spec || exit $?
